FROM docker:24.0

RUN curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" \
    -o /usr/local/bin/docker-compose && \
    chmod +x /usr/local/bin/docker-compose

COPY --from=composer:latest /usr/bin/composer /usr/local/bin/composer

RUN docker compose version
# TODO:add nginx/default config copy to prod step