FROM php:8.4-fpm

RUN apt-get update && apt-get install -y \
        libicu-dev \
    && docker-php-ext-install \
        intl \
        mysqli pdo pdo_mysql \
    && docker-php-ext-enable \
        intl \
        mysqli pdo pdo_mysql \
    && apt-get install -y git

RUN apt-get update && apt-get install -y \
    librabbitmq-dev \
    && rm -rf /var/lib/apt/lists/*

RUN pecl install amqp \
    && docker-php-ext-enable amqp


COPY --from=composer:latest /usr/bin/composer /usr/local/bin/composer