services:

    # PHP service
    app:
        build: './php'
        image: php:8.4-fpm
        container_name: php-app
        working_dir: /var/www/
        volumes:
            - ./../:/var/www
        networks:
            - app-network
        ports:
            - 9000:9000
    # MySQL database service
    db:
        image: arm64v8/mysql
        platform: linux/arm64
        container_name: mysql-db
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
        env_file:
            - ./.env
        networks:
            - app-network

    # Nginx service
    nginx:
        image: nginx:alpine
        container_name: php-nginx
        ports:
            - 80:80
        volumes:
            - ./:/var/www
            - ./nginx/conf.d/:/etc/nginx/conf.d/
        networks:
            - app-network

    rabbitmq:
        image: "rabbitmq:3-management"
        ports:
            - "5672:5672"
            - "15672:15672"
        environment:
            RABBITMQ_DEFAULT_USER: user
            RABBITMQ_DEFAULT_PASS: password

        volumes:
            - ./rabbitmq:/var/lib/rabbitmq
        restart: always

networks:
    app-network:
        driver: bridge
