FROM docker:24.0

ARG AWS_SSH_SECRET, AWS_HOST


RUN docker compose version
RUN docker-compose --version

WORKDIR /app

# Копируем все файлы, полученные через checkout в GitHub Actions, в контейнер
COPY . .

RUN install -m 600 -D /dev/null ~/.ssh/id_rsa && \
    echo $AWS_SSH_SECRET > ~/.ssh/id_rsa && \
    ssh-keyscan -H $AWS_HOST > ~/.ssh/known_hosts