name: Deploy

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  
on:
  workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-22.04
    environment: production

    steps:
      - name: Checkout 
        uses: actions/checkout@v4.1.1
        env:
          GIT_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          fetch-depth: 0

      - name: Install ssh keys
        run: |
          

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Log in to the Container registry
        uses: docker/login-action@v3.0.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker compose
        env:
          IMAGE_REF: ${{ steps.meta.outputs.tags }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_HOST: ${{ secrets.SSH_HOST }}  
        run: |
          docker run --rm ${{env.IMAGE_REF}} \
          sh -c "docker context create remote --docker host=ssh://${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} && \
          unset DOCKER_HOST && \
          docker context use remote && \
          pwd && \  
          ls -la && \
          install -m 600 -D /dev/null ~/.ssh/id_rsa && \
          echo ${{env.SSH_PRIVATE_KEY}} > ~/.ssh/id_rsa && \
          ssh-keyscan -H "${{ env.SSH_HOST }}" > ~/.ssh/known_hosts && \
          ls -la ~/.ssh/id_rsa & \  
          docker-compose --context remote -f /app/docker/docker-compose.yaml up -d"
          
          
          
#rm -rf ~/.ssh"


